/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BaseRelayRecipientContract } from './BaseRelayRecipient'
import { BetContract } from './Bet'
import { ERC20Contract } from './ERC20'
import { IERC20Contract } from './IERC20'
import { IRelayRecipientContract } from './IRelayRecipient'
import { MigrationsContract } from './Migrations'
import { ProxyBetContract } from './ProxyBet'
import { TestTokenContract } from './TestToken'

declare global {
	namespace Truffle {
		interface Artifacts {
			require(name: 'BaseRelayRecipient'): BaseRelayRecipientContract
			require(name: 'Bet'): BetContract
			require(name: 'ERC20'): ERC20Contract
			require(name: 'IERC20'): IERC20Contract
			require(name: 'IRelayRecipient'): IRelayRecipientContract
			require(name: 'Migrations'): MigrationsContract
			require(name: 'ProxyBet'): ProxyBetContract
			require(name: 'TestToken'): TestTokenContract
		}
	}
}

export { BaseRelayRecipientContract, BaseRelayRecipientInstance } from './BaseRelayRecipient'
export { BetContract, BetInstance } from './Bet'
export { ERC20Contract, ERC20Instance } from './ERC20'
export { IERC20Contract, IERC20Instance } from './IERC20'
export { IRelayRecipientContract, IRelayRecipientInstance } from './IRelayRecipient'
export { MigrationsContract, MigrationsInstance } from './Migrations'
export { ProxyBetContract, ProxyBetInstance } from './ProxyBet'
export { TestTokenContract, TestTokenInstance } from './TestToken'
